//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LocationHelper.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LocationHelper.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configured Sheet number does not exists in the supplied file..
        /// </summary>
        internal static string FrmLocationHelper__ProcessData_Configured_Sheet_number_does_not_exists_in_the_supplied_file {
            get {
                return ResourceManager.GetString("FrmLocationHelper__ProcessData_Configured_Sheet_number_does_not_exists_in_the_sup" +
                        "plied_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception occured while closing the excel application..
        /// </summary>
        internal static string FrmLocationHelper__ProcessData_Exception_occured_while_closing_the_excel_application_ {
            get {
                return ResourceManager.GetString("FrmLocationHelper__ProcessData_Exception_occured_while_closing_the_excel_applicat" +
                        "ion_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Path Error.
        /// </summary>
        internal static string FrmLocationHelper_btnProcess_Click_File_Path_Error {
            get {
                return ResourceManager.GetString("FrmLocationHelper_btnProcess_Click_File_Path_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid File Path.
        /// </summary>
        internal static string FrmLocationHelper_btnProcess_Click_Invalid_File_Path {
            get {
                return ResourceManager.GetString("FrmLocationHelper_btnProcess_Click_Invalid_File_Path", resourceCulture);
            }
        }
    }
}
